### ISSUE TITLE
Ⅰ 村子里最好的剑 | 芳文社厨hookan的咖啡厅

### ISSUE THREAD

**Issue by Hookan** [Hookan/BlogComment#6]
http://blog.hookan.top/2017/12/25/forge1/

**Comment by Stars-sea** [comment]
emmm... 为什么到给方块加材质这里总会报错
json是这样写的
blockstates\crystal.json:
```blockstates\crystal.json
{
  "variants": {
    "normal": { "model": "tool:crystal" }
  }
} 
```
models\block\crystal.json:
```models\block\crystal.json
{
  "parent": "block/cube_all",
  "textures": {
    "all": "tool:blocks/crystal"
  }
}
```
models\item\crystal.json:
```models\item\crystal.json
{
  "parent": "tool:block/crystal"
}
```
为什么总是报错
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tool Mod (tool)
Caused by: java.lang.NullPointerException
        at net.minecraft.client.renderer.block.model.ModelResourceLocation.<init>(ModelResourceLocation.java:24)
        at starsea.tool.common.block.ToolBlocks.clientInit(ToolBlocks.java:25)
        at starsea.tool.client.ClientProxy.perInit(ClientProxy.java:16)
        at starsea.tool.Tool.preInit(Tool.java:33)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
        at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
        at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
        at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
        at net.minecraft.client.Minecraft.init(Minecraft.java:514)
        at net.minecraft.client.Minecraft.run(Minecraft.java:422)
        at net.minecraft.client.main.Main.main(Main.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
        at GradleStart.main(GradleStart.java:25)
```

**Comment by 1440634291** [comment]
> emmm... 为什么到给方块加材质这里总会报错
> json是这样写的
> blockstates\crystal.json:
> 
> ```json
> {
>   "variants": {
>     "normal": { "model": "tool:crystal" }
>   }
> } 
> ```
> 
> models\block\crystal.json:
> 
> ```json
> {
>   "parent": "block/cube_all",
>   "textures": {
>     "all": "tool:blocks/crystal"
>   }
> }
> ```
> 
> models\item\crystal.json:
> 
> ```json
> {
>   "parent": "tool:block/crystal"
> }
> ```
> 
> 为什么总是报错
> 
> ```
> net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Tool Mod (tool)
> Caused by: java.lang.NullPointerException
>         at net.minecraft.client.renderer.block.model.ModelResourceLocation.<init>(ModelResourceLocation.java:24)
>         at starsea.tool.common.block.ToolBlocks.clientInit(ToolBlocks.java:25)
>         at starsea.tool.client.ClientProxy.perInit(ClientProxy.java:16)
>         at starsea.tool.Tool.preInit(Tool.java:33)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:639)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
>         at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
>         at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
>         at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
>         at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
>         at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
>         at com.google.common.eventbus.EventBus.post(EventBus.java:217)
>         at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
>         at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
>         at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
>         at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
>         at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
>         at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
>         at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
>         at com.google.common.eventbus.EventBus.post(EventBus.java:217)
>         at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
>         at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
>         at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
>         at net.minecraft.client.Minecraft.init(Minecraft.java:514)
>         at net.minecraft.client.Minecraft.run(Minecraft.java:422)
>         at net.minecraft.client.main.Main.main(Main.java:118)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
>         at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:498)
>         at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
>         at GradleStart.main(GradleStart.java:25)
> ```

我也和你一样的错误，试了好久发现在CommonProxy类中的preInit方法加上RedoBlocks.init();就能通过了
